project:
  type: website
  output-dir: _site
  resources:
    - "_data/people.yml"   # <-- make publicly available
    - "assets/instruments/**" # Instruments images
    - assets/**            # ensure assets are published
    - _data/**

website:
  title: "ADALab"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Instruments
        href: instruments.qmd  
      - text: People
        href: people.qmd
      - text: Projects
        href: projects.qmd
      - text: Publications
        href: publications.qmd
      - text: News
        href: news.qmd
      - text: Tools
        href: tools.qmd
      - text: Contact
        href: contact.qmd

metadata-files:
  - _data/people.yml
  - _data/projects.yml

format:
  html:
    theme: cosmo
    toc: true
    css: assets/css/style.css

# bibliography config (global, but hidden by default)
bibliography: _data/publications.bib
csl: assets/css/apa-old-doi-prefix.csl
link-citations: true
suppress-bibliography: true    # â† hide References on all pages by default